/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { AdditionalService } from './AdditionalService';
import type { BookingTransfer } from './BookingTransfer';
import type { GiftRecipient } from './GiftRecipient';
import type { Service } from './Service';
import type { Status } from './Status';
import type { User } from './User';
import type { Voucher } from './Voucher';
export type Booking = {
  id?: string;
  dateCreated?: string;
  dateModified?: string;
  userId?: string;
  user?: User;
  serviceId?: string;
  bookingReference?: string | null;
  service?: Service;
  date?: string;
  time?: string;
  durationMinutes?: number;
  endDateTime?: string;
  amount?: number;
  tax?: number;
  totalAmount?: number;
  rejectionReason?: string | null;
  status?: Status;
  statusId?: number;
  amountBeforeDiscount?: number;
  isGift?: boolean;
  giftRecipientId?: string | null;
  giftRecipient?: GiftRecipient;
  voucherId?: string | null;
  voucher?: Voucher;
  bookingType?: string | null;
  locationType?: string | null;
  clientAddress?: string | null;
  virtualMeetingLink?: string | null;
  participantCount?: number;
  participantDetails?: string | null;
  preBookingAnswers?: string | null;
  specialRequests?: string | null;
  parentBookingId?: string | null;
  parentBooking?: Booking;
  recurringBookings?: Array<Booking> | null;
  recurrencePattern?: string | null;
  recurrenceEndDate?: string | null;
  packageBookingId?: string | null;
  sessionNumber?: number | null;
  totalSessions?: number | null;
  depositAmount?: number | null;
  depositPaid?: number | null;
  isDepositPaid?: boolean;
  depositPaidDate?: string | null;
  cancelledDate?: string | null;
  cancellationReason?: string | null;
  cancellationFee?: number | null;
  rescheduledFromDate?: string | null;
  rescheduleReason?: string | null;
  completedDate?: string | null;
  completionNotes?: string | null;
  followUpSent?: boolean;
  followUpSentDate?: string | null;
  bookingSource?: string | null;
  bookingNotes?: string | null;
  isManualBooking?: boolean;
  clientFirstName?: string | null;
  clientLastName?: string | null;
  clientEmail?: string | null;
  clientPhone?: string | null;
  isPaymentReceived?: boolean;
  paymentMethod?: string | null;
  paymentReference?: string | null;
  additionalServices?: Array<AdditionalService> | null;
  bookingTransferId?: string | null;
  bookingTransfer?: BookingTransfer;
};

